= Helm Chart Intershop Commerce Management - Web Adapter and Web Adapter Agent

Installs the ICM Web Adapter and Web Adapter agent independently.

== Prerequisites Details

* Helm
* kubectl
* Kubernetes 1.14+

== Chart Details

This chart will do the following:

* Deploy an ICM Web Adapter and Web Adapter Agent

== Installing the Chart

=== Docker Pull Secret

Create a secret for the Docker registry from which the images are coming. The secret's name must match the configured secret under `imagePullSecrets` within the application deployment. The default secret name is `dockerhub`.

[source,bash]
----
kubectl create secret docker-registry <yourDockerRegistryName> --docker-server=<yourDockerRegistryServer> --docker-username=<yourUsername> --docker-password=<yourPassword> --docker-email=<yourEmail>
----

=== Persistence

==== PageCache

`local`, `cluster`, `azurefiles`, `nfs`, `existingClaim` are possible persistence types.
The default is `local`, where `persistence.pagecache.local.path` must be set to a valid local folder.

=== Add the Intershop Helm Repository

Before installing Intershop Helm charts, add the https://intershop.github.io/helm-charts[Intershop helm-charts repository] to your Helm client.

[source,bash]
----
helm repo add intershop https://intershop.github.io/helm-charts
helm repo update
----

=== Install Chart

To install the chart with the release name `icm-web`:

[source,bash]
----
helm install my-release intershop/icm-web --values=values.yaml --namespace icm-web
----

== Detailed Documentation

* link:docs/values-yaml/[values.yaml] documentation
