apiVersion: v2
description: Intershop Commerce Management - ICM Test Chart
name: icm-test
version: 2.2.0
annotations:
  requestedMemoryQuota: 6100Mi
  requestedCpuQuotaInMinutes: "2200"
dependencies:
  - name: icm
    version: 3.2.0
    repository: file://../icm
