= Helm Chart Intershop Commerce Management - ICM Test

This chart is able to test the icm chart functionality.

== Prerequisites Details

* Helm
* kubectl
* Kubernetes 1.14+

== Chart Details

This chart will do the following:

* Deploy an ICM Application Server using the link:../icm-as/README.md[intershop/icm-as] chart
* Deploy an ICM Web Adapter and Web Adapter Agent using the link:../icm-web/README.md[intershop/icm-web] chart

== Running the Chart locally

To run the chart locally, refer to the the documentation on link:./docs/local-execution.asciidoc[local execution].

== Installing the Chart

=== Docker Pull Secret

Create a secret for the Docker registry from which the images are coming. The secret's name must match the configured secret under `image.secret` within the application deployment. The default secret name is `dockerhub`.

[source,bash]
----
kubectl create secret docker-registry <yourDockerRegistryName> --docker-server=<yourDockerRegistryServer> --docker-username=<yourUsername> --docker-password=<yourPassword> --docker-email=<yourEmail>
----

=== Persistence

==== Sites

`local`, `cluster`, `azurefiles`, `nfs`, `existingClaim` are possible persistence options.
The default is `local`, where `persistence.sites.local.path` must be set to a valid local folder.

=== Database

The necessary database connection can be configured in the `database` section. The chart also supports deploying a (containerized) MSSQL database. If enabled, the deployed MSSQL database is used instead of the one configured in the `database` section.

=== Add the Intershop Helm Repository

Before installing Intershop Helm charts, add the https://intershop.github.io/helm-charts[Intershop helm-charts repository] to your Helm client.

[source,bash]
----
helm repo add intershop https://intershop.github.io/helm-charts
helm repo update
----

=== Install Chart

To install the chart with the release name `icm-test`:

[source,bash]
----
helm install icm-test intershop/icm-test --values=values.yaml
----

=== Install Chart via Cloned helm-charts Repository

[source,bash]
----
cd charts
helm dependency update icm
helm install my-release ./icm --values=values.yaml --namespace icm
----

== Testing ICM

This helm chart also allows you to execute Intershop HtmlUnit tests via a testrunner.

=== Execute Locally

There are already preconfigured value-files for local test execution, orchestrated by a bash script.
Follow these steps to execute a test:

. Be sure that each included chart is up-to-date:
+
[source,bash]
----
helm dependency update ../icm-as
helm dependency update .
----

. Create the necessary k8s secrets for icm-web and icm-as (e.g., `kubectl create secret docker-registry dockerhub --docker-username=<your username> --docker-password=<your password> --docker-email=<your email>`)
. Run: `./start-test-local.sh` and follow the instructions.

=== Local Execution Guide

For detailed instructions on local execution, see link:docs/local-execution.asciidoc[Local Execution Guide].