kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "pwa.componentName" (dict "root" . "component" "proxy") }}-gomplate-datasources
  labels:
    app.kubernetes.io/name: {{ include "pwa.componentName" (dict "root" . "component" "proxy") }}
    helm.sh/chart: {{ include "pwa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if .Values.proxy.multiChannel }}
  multi-channel.yaml: {{- .Values.proxy.multiChannel | toYaml | indent 4}}
  {{- else }}
  multi-channel.yaml: |-
    .+:
      channel: default
  {{- end -}}
  {{- if .Values.proxy.cacheIgnoreParams }}
  caching-ignore-params.yaml: {{- .Values.proxy.cacheIgnoreParams | toYaml | indent 4}}
  {{- else }}
  caching-ignore-params.yaml: |-
    params: []
  {{- end -}}
  {{- if .Values.proxy.additionalHeaders }}
  additional-headers.yaml: {{- .Values.proxy.additionalHeaders | toYaml | indent 4}}
  {{- else }}
  additional-headers.yaml: |-
    headers: []
  {{- end -}}
