= Documentation about the `values.yaml` attributes belonging to section `appServerConnection`
// GitHub issue: https://github.com/github/markup/issues/1095

:icons: font

ifdef::backend-html5[]
++++
<style>
.mand {
  color: #e00000;
}
.opt {
  color: #b0adac;
}
.cond {
  color: #FFDC00;
}
.tag-audience {
  font-style: italic;
}
.tag-audience::before {
  content: "@Target Audience: ";
}
.tag-since {
  font-style: italic;
}
.tag-since::before {
  content: "@Since: ";
}
.tag-deprecated {
  font-style: italic;
}
.tag-deprecated::before {
  content: "@Deprecated: ";
}
.placeholder {
  font-style: italic;
}
.placeholder::before {
  content: "<";
}
.placeholder::after {
  content: ">";
}
</style>
++++
endif::[]

:mandatory: icon:check[role="mand"]
:optional: icon:times[role="opt"]
:conditional: icon:question[role="cond"]


=== Description

All the `icm-web-wa` pods are required to send requests to the deployed `icm-as-server` pods. These pods are reachable using the appropriate service. So the `icm-web-wa` needs to know the name of that service and the used port.

The `appServerConnection` section contains the following attributes:

[cols="1,3,1,1,1",options="header"]
|===
|Attribute |Description |Type |Mandatory |Default Value
|serviceName|the name of the service|string|{optional}|`icm-as`
|port|the management (`mgnt`) port|string|{optional}|`7744`
|===

[TIP]
====
See the `icm-as` chart for details about the link:../../../icm-as/docs/values-yaml/no-section.asciidoc#_example_icmAsServiceNaming[service naming].
====

=== Example

[source,yaml]
----
appServerConnection:
  serviceName: icm-as
  port: 7744
----

This configures the `icm-web-wa` to connect to the service `icm-as` on port `7744`.
