= Documentation about the `values.yaml` attributes belonging to section `configMapMounts`
// GitHub issue: https://github.com/github/markup/issues/1095

:icons: font

ifdef::backend-html5[]
++++
<style>
.mand {
  color: #e00000;
}
.opt {
  color: #b0adac;
}
.cond {
  color: #FFDC00;
}
.tag-audience {
  font-style: italic;
}
.tag-audience::before {
  content: "@Target Audience: ";
}
.tag-since {
  font-style: italic;
}
.tag-since::before {
  content: "@Since: ";
}
.tag-deprecated {
  font-style: italic;
}
.tag-deprecated::before {
  content: "@Deprecated: ";
}
.placeholder {
  font-style: italic;
}
.placeholder::before {
  content: "<";
}
.placeholder::after {
  content: ">";
}
</style>
++++
endif::[]

:mandatory: icon:check[role="mand"]
:optional: icon:times[role="opt"]
:conditional: icon:question[role="cond"]


=== Description

Allows to mount values stored in Kubernetes https://kubernetes.io/docs/concepts/configuration/configmap/[configMaps] to be mounted as files inside the `icm-web-wa` container. The `configMapMounts` section is a list of objects containing the following attributes:

[cols="1,3,1,1,1",options="header"]
|===
|Attribute |Description |Type |Mandatory |Default Value
|name|the name of the volume mount to be used|string|{mandatory}|-
|configMapName|the name of the https://kubernetes.io/docs/concepts/configuration/configmap/[configMap]|string|{mandatory}|-
|mountPath|absolute path of the folder where to mount the file. The complete file path is then [.placeholder]#`mountPath`#/[.placeholder]#`fileName`#.|path|{mandatory}|-
|fileName|name of the file inside the Kubernetes https://kubernetes.io/docs/concepts/configuration/configmap/[configMap]|path|{mandatory}|-
|fileMode|https://www.linuxfoundation.org/blog/blog/classic-sysadmin-understanding-linux-file-permissions[file permissions] of the mounted file|file permissions (octal)|{optional}|`440`
|readOnly|if `true` the file is mounted read-only|string|{optional}|`false`
|===

[CAUTION]
====
Mounted files will hide files that are already present in the target directory coming out of the container image. Pay attention to not overwrite important files.
====

=== Example

[source,yaml]
----
configMapMounts:
  - name: httpd-config <1>
    configMapName: icm-web-httpd-conf <2>
    mountPath: /intershop/conf/httpd <3>
    fileName: httpd.conf <3>
    fileMode: 440 <4>
    readOnly: true <5>
----

Given the https://kubernetes.io/docs/concepts/configuration/configmap/[configMap] `icm-web-httpd-conf` containing the file `httpd.conf` zhe configuration above _overwrites_ the default `/intershop/conf/httpd/httpd.conf`-file by from this https://kubernetes.io/docs/concepts/configuration/configmap/[configMap]:

<1> use mount name `httpd-config`
<2> get data from https://kubernetes.io/docs/concepts/configuration/configmap/[configMap] `icm-web-httpd-conf`
<3> reference configMap entry `httpd.conf` and make it available at `/intershop/conf/httpd/httpd.conf`
<4> set file permissions to `440` (readable by owner and group, not writable)
<5> mount the file read-only (somehow redundant because of the file permissions)
