= Documentation about the `values.yaml` attributes belonging to section `environment`
// GitHub issue: https://github.com/github/markup/issues/1095

:icons: font

ifdef::backend-html5[]
++++
<style>
.mand {
  color: #e00000;
}
.opt {
  color: #b0adac;
}
.cond {
  color: #FFDC00;
}
.tag-audience {
  font-style: italic;
}
.tag-audience::before {
  content: "@Target Audience: ";
}
.tag-since {
  font-style: italic;
}
.tag-since::before {
  content: "@Since: ";
}
.tag-deprecated {
  font-style: italic;
}
.tag-deprecated::before {
  content: "@Deprecated: ";
}
.placeholder {
  font-style: italic;
}
.placeholder::before {
  content: "<";
}
.placeholder::after {
  content: ">";
}
</style>
++++
endif::[]

:mandatory: icon:check[role="mand"]
:optional: icon:times[role="opt"]
:conditional: icon:question[role="cond"]


=== Description

Allows to define environment variables for `icm-web-wa` and `icm-web-waa` containers. The environment variables are defined as a yaml object containing attributes that define the variable's name and value. The attribute's name itself is used as the environment variable's name and the value as its value.

The environment variables are explained in detail for the `icm-as` Helm Chart so just see link:../../../icm-as/docs/values-yaml/environment.asciidoc[here].
