= Documentation about the `values.yaml` attributes belonging to section `imagePullSecrets`
// GitHub issue: https://github.com/github/markup/issues/1095

:icons: font

ifdef::backend-html5[]
++++
<style>
.mand {
  color: #e00000;
}
.opt {
  color: #b0adac;
}
.cond {
  color: #FFDC00;
}
.tag-audience {
  font-style: italic;
}
.tag-audience::before {
  content: "@Target Audience: ";
}
.tag-since {
  font-style: italic;
}
.tag-since::before {
  content: "@Since: ";
}
.tag-deprecated {
  font-style: italic;
}
.tag-deprecated::before {
  content: "@Deprecated: ";
}
.placeholder {
  font-style: italic;
}
.placeholder::before {
  content: "<";
}
.placeholder::after {
  content: ">";
}
</style>
++++
endif::[]

:mandatory: icon:check[role="mand"]
:optional: icon:times[role="opt"]
:conditional: icon:question[role="cond"]


=== Description

Lists the https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod[image pull secrets] available when pulling Docker images. So the section is a yaml array containing 0 to n string entry. Each entry is the name of a Kubernetes secret that contains credentials to access a Docker registry.

The image pull secrets already are explained in detail for the `icm-as` Helm Chart so just see link:../../../icm-as/docs/values-yaml/image-pull-secrets.asciidoc[here].
