= Documentation about the `values.yaml` attributes belonging to section `podSecurityContext`

// GitHub issue: https://github.com/github/markup/issues/1095

:icons: font

ifdef::backend-html5[]
++++
<style>
.mand {
  color: #e00000;
}
.opt {
  color: #b0adac;
}
.cond {
  color: #FFDC00;
}
.tag-audience {
  font-style: italic;
}
.tag-audience::before {
  content: "@Target Audience: ";
}
.tag-since {
  font-style: italic;
}
.tag-since::before {
  content: "@Since: ";
}
.tag-deprecated {
  font-style: italic;
}
.tag-deprecated::before {
  content: "@Deprecated: ";
}
.placeholder {
  font-style: italic;
}
.placeholder::before {
  content: "<";
}
.placeholder::after {
  content: ">";
}
</style>
++++
endif::[]

:mandatory: icon:check[role="mand"]
:optional: icon:times[role="opt"]
:conditional: icon:question[role="cond"]


=== Description

Configures the https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[security context] to be used by the `icm-wa` pod. The attributes of the `podSecurityContext` section are defined by https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.33/#podsecuritycontext-v1-core. The attribute values are used as is for the `securityContext` of the `icm-wa` pod.

The security context already is explained in detail for the `icm-as` Helm Chart so just see link:../../../icm-as/docs/values-yaml/pod-security-context.asciidoc[here].
