{{- $root := . }}
{{- range $route := list "public" "management" "control" }}
{{- $settings := index $root.Values.ingress $route }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "media.name" $root }}-{{ $route }}
  {{- with $settings.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $root.Values.ingress.className | quote }}
  tls:
    - hosts: [{{ $settings.host | quote }}]
      secretName: {{ $settings.tlsSecret | quote }}
  rules:
    - host: {{ $settings.host | quote }}
      http:
        paths:
          {{- if eq $route "public" }}
          - path: /mediawidget/public/tenants/
            pathType: Prefix
            backend:
              service:
                name: {{ include "media.name" $root }}-widget{{ if $root.Values.httpScaling.widget.enabled }}-interceptor{{ end }}
                port: {number: {{ if $root.Values.httpScaling.widget.enabled }}{{ $root.Values.httpScaling.interceptor.port }}{{ else }}8080{{ end }}}
          - path: /imgproxy/
            pathType: Prefix
            backend:
              service:
                name: {{ include "media.name" $root }}-imgproxy
                port: {number: 8080}
          {{- else }}
          - path: {{ if eq $route "management" }}/mediawidget{{ else }}/{{ end }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "media.name" $root }}-{{ if eq $route "control" }}control-api{{ else }}widget{{ if $root.Values.httpScaling.widget.enabled }}-interceptor{{ end }}{{ end }}
                port: {number: {{ if and (eq $route "management") $root.Values.httpScaling.widget.enabled }}{{ $root.Values.httpScaling.interceptor.port }}{{ else }}8080{{ end }}}
          {{- end }}
{{- end }}
