{{- $root := . }}
{{- range $role := list "widget" "rest" }}
{{- if (index $root.Values.httpScaling $role).enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "media.name" $root }}-{{ $role }}-interceptor
spec:
  type: ExternalName
  externalName: {{ printf "%s.%s.svc.%s" $root.Values.httpScaling.interceptor.service $root.Values.httpScaling.interceptor.namespace $root.Values.httpScaling.clusterDomain | quote }}
  ports:
    - {name: http, port: {{ $root.Values.httpScaling.interceptor.port }}, protocol: TCP}
{{- end }}
{{- end }}
