{{- $root := . }}
{{- range $role, $component := .Values.components }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "media.name" $root }}-{{ include "media.component" $role }}
  annotations:
    azure.workload.identity/client-id: {{ $component.clientId | quote }}
    azure.workload.identity/tenant-id: {{ $root.Values.azure.tenantId | quote }}
automountServiceAccountToken: false
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "media.name" . }}-imgproxy
  annotations:
    azure.workload.identity/client-id: {{ .Values.imgproxy.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.azure.tenantId | quote }}
automountServiceAccountToken: false
