= Documentation about the `values.yaml` attributes belonging to section `dockerSecret`
// GitHub issue: https://github.com/github/markup/issues/1095

:icons: font

ifdef::backend-html5[]
++++
<style>
.mand {
  color: #e00000;
}
.opt {
  color: #b0adac;
}
.cond {
  color: #FFDC00;
}
.tag-audience {
  font-style: italic;
}
.tag-audience::before {
  content: "@Target Audience: ";
}
.tag-since {
  font-style: italic;
}
.tag-since::before {
  content: "@Since: ";
}
.tag-deprecated {
  font-style: italic;
}
.tag-deprecated::before {
  content: "@Deprecated: ";
}
.placeholder {
  font-style: italic;
}
.placeholder::before {
  content: "<";
}
.placeholder::after {
  content: ">";
}
</style>
++++
endif::[]

:mandatory: icon:check[role="mand"]
:optional: icon:times[role="opt"]
:conditional: icon:question[role="cond"]


[.tag-audience]#Developer, Tester#

=== Description

Configures a https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets[docker config secret] to be deployed. The secret is meant to contain credentials to login into a Docker registry. So it then can be used as an link:values-yaml/image-pull-secrets.asciidoc[imagePullSecret].

[cols="1,3,1,1,1",options="header"]
|===
|Attribute |Description |Type |Mandatory |Default Value
|enabled|enable/disable the secret deployment|boolean|{optional}|`false`
|name|name of the secret|string|{mandatory}|-
|username|user name|string|{mandatory}|-
|password|password|string|{mandatory}|-
|===

=== Example

[source,yaml]
----
dockerSecret:
  enabled: true
  name: "dockerhub" <1>
  username: "username" <2>
  password: "topsecret" <3>
----
This example deploys a secret using:

<1> name: `dockerhub`
<2> user name: `username`
<3> password: `topsecret`

[WARNING]
====
Deploying a secret this way requires to store the password in plain text in the `values.yaml` file. This is not recommended for production use. Instead, follow the https://support.intershop.com/kb/index.php/Display/X31381[Guide - Secret Store Process] to create a Kubernetes secret from a Key Vault secret.
====