= Documentation about the `values.yaml` attributes belonging to section `operationalContext`
// GitHub issue: https://github.com/github/markup/issues/1095

:icons: font

ifdef::backend-html5[]
++++
<style>
.mand {
  color: #e00000;
}
.opt {
  color: #b0adac;
}
.cond {
  color: #FFDC00;
}
.tag-audience {
  font-style: italic;
}
.tag-audience::before {
  content: "@Target Audience: ";
}
.tag-since {
  font-style: italic;
}
.tag-since::before {
  content: "@Since: ";
}
.tag-deprecated {
  font-style: italic;
}
.tag-deprecated::before {
  content: "@Deprecated: ";
}
.placeholder {
  font-style: italic;
}
.placeholder::before {
  content: "<";
}
.placeholder::after {
  content: ">";
}
</style>
++++
endif::[]

:mandatory: icon:check[role="mand"]
:optional: icon:times[role="opt"]
:conditional: icon:question[role="cond"]


=== Description

Configures the operational context (aka _environment_) the ICM is running in. The following attributes are available:

[cols="1,3,1,1,1",options="header"]
|===
|Attribute |Description |Type |Mandatory |Default Value
|customerId|the id of the customer|string|{mandatory}|`n_a` (default value for compatibility with older versions)
|environmentType|the type of the environment e.g.int,uat,prd|string|{optional}|`prd`
|environmentName|the name of the environment (environment-type + some sort of id, e.g. int-01)|string|{optional}|[.placeholder]#value of `environmentType`#
|===

Using these attribute and some additional information from section link:replication.asciidoc[`replication`] the `operationalContextName` is calculated as follows:

[.placeholder]#`customerId`#-[.placeholder]#`environmentName`#-[.placeholder]#`stagingType`#

with `stagingType` calculated as follows:

----
if replication.enabled=true then
  if replication.role=source then
    stagingType=edit
  else
    stagingType=live
else
  stagingType=standalone
----

=== Example

[source,yaml]
----
operationalContext:
  customerId: "myshop"
  environmentType: "uat"
  environmentName: "uat-01"

replication:
  enabled: true
  role: source
----

This example would result in the `operationalContextName` being `myshop-uat-01-edit`.
