= Documentation about the `values.yaml` attributes belonging to section `podSecurityContext`

// GitHub issue: https://github.com/github/markup/issues/1095

:icons: font

ifdef::backend-html5[]
++++
<style>
.mand {
  color: #e00000;
}
.opt {
  color: #b0adac;
}
.cond {
  color: #FFDC00;
}
.tag-audience {
  font-style: italic;
}
.tag-audience::before {
  content: "@Target Audience: ";
}
.tag-since {
  font-style: italic;
}
.tag-since::before {
  content: "@Since: ";
}
.tag-deprecated {
  font-style: italic;
}
.tag-deprecated::before {
  content: "@Deprecated: ";
}
.placeholder {
  font-style: italic;
}
.placeholder::before {
  content: "<";
}
.placeholder::after {
  content: ">";
}
</style>
++++
endif::[]

:mandatory: icon:check[role="mand"]
:optional: icon:times[role="opt"]
:conditional: icon:question[role="cond"]


=== Description

Configures the https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[security context] to be used by the `icm-as-server` and `jobserver` pods. The attributes of the `podSecurityContext` section are defined by https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.33/#podsecuritycontext-v1-core. The attribute values are used as is for the `securityContext`s of the `icm-as-server` and the `jobserver` pods.

[NOTE]
====
There are 2 special attributes: `runAsUser` and `runAsGroup`. These are additionally applied to all volumes that use the storage type <<persistence.asciidoc#_azurefilesType, azurefiles>>.
====

=== Default

[source,yaml]
----
podSecurityContext:
  runAsUser: 150
  runAsGroup: 150
  fsGroup: 150
  runAsNonRoot: true
  fsGroupChangePolicy: "OnRootMismatch"
----
