= Documentation about the `values.yaml` attributes belonging to section `secrets`
// GitHub issue: https://github.com/github/markup/issues/1095

:icons: font

ifdef::backend-html5[]
++++
<style>
.mand {
  color: #e00000;
}
.opt {
  color: #b0adac;
}
.cond {
  color: #FFDC00;
}
.tag-audience {
  font-style: italic;
}
.tag-audience::before {
  content: "@Target Audience: ";
}
.tag-since {
  font-style: italic;
}
.tag-since::before {
  content: "@Since: ";
}
.tag-deprecated {
  font-style: italic;
}
.tag-deprecated::before {
  content: "@Deprecated: ";
}
.placeholder {
  font-style: italic;
}
.placeholder::before {
  content: "<";
}
.placeholder::after {
  content: ">";
}
</style>
++++
endif::[]

:mandatory: icon:check[role="mand"]
:optional: icon:times[role="opt"]
:conditional: icon:question[role="cond"]


[.tag-deprecated]#since 2.9.0, use link:secret-mounts.asciidoc[secretMounts] instead#

=== Description

Allows the content of Kubernetes secrets to be mounted made available as environment variables to the `icm-as-server` container.
The `secrets` section is a list of objects containing the following attributes:

[cols="1,3,1,1,1",options="header"]
|===
|Attribute |Description |Type |Mandatory |Default Value
|name|the name of the secret|string|{mandatory}|-
|key|the data field inside the secret|string|{mandatory}|-
|env|name of the environment variable to get made available|string|{mandatory}|-
|===

=== Example

[source,yaml]
----
secrets:
  - name: my-secret <1>
    key: data
    env: MY_SECRET
  - name: other-secret <2>
    key: password
    env: MY_PASSWORD
----

The configuration makes the 2 secrets `my-secret` and `other-secret` available as environment variables:

<1> `my-secret` is made available as environment variable `MY_SECRET`
<2> `other-secret` is made available as environment variable `MY_PASSWORD`

[NOTE]
====
See https://support.intershop.com/kb/index.php/Display/X31381[Guide - Secret Store Process] for details on how to make secrets from an Azure KeyVault available in K8s secrets.
====
