= Documentation about the `values.yaml` attributes belonging to section `serviceAccount`
// GitHub issue: https://github.com/github/markup/issues/1095

:icons: font

ifdef::backend-html5[]
++++
<style>
.mand {
  color: #e00000;
}
.opt {
  color: #b0adac;
}
.cond {
  color: #FFDC00;
}
.tag-audience {
  font-style: italic;
}
.tag-audience::before {
  content: "@Target Audience: ";
}
.tag-since {
  font-style: italic;
}
.tag-since::before {
  content: "@Since: ";
}
.tag-deprecated {
  font-style: italic;
}
.tag-deprecated::before {
  content: "@Deprecated: ";
}
.placeholder {
  font-style: italic;
}
.placeholder::before {
  content: "<";
}
.placeholder::after {
  content: ">";
}
</style>
++++
endif::[]

:mandatory: icon:check[role="mand"]
:optional: icon:times[role="opt"]
:conditional: icon:question[role="cond"]


=== Description

Allows the deployment of a https://kubernetes.io/docs/concepts/security/service-accounts/[`serviceAccount`] that can be used for https://azure.github.io/azure-workload-identity/docs/[workload identity] support. The following table lists the attributes of the `serviceAccount` section:

[cols="1,3,1,1,1",options="header"]
|===
|Attribute |Description |Type |Mandatory |Default Value
|create|enables/disables the deployment of the service account|boolean|{optional}|`false`
|name|name of the service account|string|{optional}|[.placeholder]#fullname#-default
|annotations|annotations to be applied to the ingress configuration|<<_annotations,Annotations>>|{optional}|`{}`
|===

[TIP]
====
For details on `fullname` see the link:no-section.asciidoc#_example_nameOverride[nameOverride and fullnameOverride]
====

[#_annotations]
==== Type `Annotations`

The type `Annotations` is a yaml object containing key-value pairs that are applied as annotations. It contains the following attributes:

===== Example
[source,yaml]
----
annotations:
  annotation0: value0
  ...
  annotationn: valuen
----

=== Example

[source,yaml]
----
serviceAccount:
  create: true
  name: "my-service-account"
  annotations:
    annotation0: value0
    ...
    annotationn: valuen
----

