= Documentation about the `values.yaml` attributes belonging to section `webLayer`
include::definitions.include[]

=== Description

Configures if the `icm-as` is configured to process requests on its own (without the `webadapter`) and how to do so. The following table lists the attributes of the `webLayer` section:

[CAUTION]
====
Enabling the `webLayer` only makes sense if the link:ingress.asciidoc[`ingress`] is also enabled. Otherwise, the `icm-as` will not be able to process the requests as expected.
====

[cols="1,3,1,1,1",options="header"]
|===
|Attribute |Description |Type |Mandatory |Default Value
|enabled|enables/disables the `webLayer`|boolean|{optional}|`false`
|redis|enablement and configuration of a https://redis.io/[redis]-cache|<<_redis,Redis>>|{optional}|`redis.enabled=false`
|===

[#_redis]
==== Type `Redis`

The type `Redis` enables/disables and configures a https://redis.io/[redis]-cache client to be used to connect to a https://redis.io/[redis]-server which is used to cache HTTP responses. It contains the following attributes:

[cols="1,3,1,1,1",options="header"]
|===
|Attribute |Description |Type |Mandatory |Default Value
|enabled|enable/disable the redis|boolean|{optional}|`false`
|config|configures the https://redisson.pro/docs/configuration/#using-yaml[redis client] inside the `icm-as`|https://redisson.pro/docs/configuration/#using-yaml[redis client config]|{optional}|[.placeholder]#see below#
|===

[source,yaml]
.Default `config`
----
singleServerConfig:
  timeout: 50
  retryAttempts: 1
  retryInterval: 50
  address: "redis://<.Release.Name>-redis-headless:6379" <1>
----

<1> Requires a redis server to be running and accessible at the given address.

=== Example

[source,yaml]
----
webLayer:
  enabled: true
  redis:
    enabled: true
----
