{{- if .Values.job.enabled -}}
{{- $legacyJobValues := omit .Values.job "enabled" "servers" -}}
{{- $jobServers := .Values.job.servers | default (dict) -}}
{{- if eq (len $jobServers) 0 -}}
{{- $values_ := set $jobServers "default" (dict) -}}
{{- end -}}
{{- $jobServerKeys := keys $jobServers | sortAlpha -}}
{{- range $jobServerKey := $jobServerKeys -}}
{{- $jobConfig := (get $jobServers $jobServerKey) | default (dict) -}}
{{- $effectiveJobValues := mergeOverwrite (deepCopy $legacyJobValues) (deepCopy $jobConfig) -}}
{{/* Build values based on main values merged with job specific ones */}}
{{- $jobValues:= deepCopy $ -}}
{{- $effectiveValues := mergeOverwrite (deepCopy $.Values) (deepCopy $effectiveJobValues) -}}
{{- $_ := set $jobValues "Values" $effectiveValues -}}
{{- if $effectiveValues.serverGroup -}}
{{- $_ := set $jobValues "jobServerGroup" $effectiveValues.serverGroup -}}
{{- else -}}
{{- $_ := set $jobValues "jobServerGroup" "JOB" -}}
{{- end -}}
{{- if $effectiveValues.serverName -}}
{{- $_ := set $jobValues "jobServerName" $effectiveValues.serverName -}}
{{- else -}}
{{- $_ := set $jobValues "jobServerName" "jobserver" -}}
{{- $_ := set $effectiveValues "serverName" "jobserver" -}}
{{- end -}}
{{- $ctx := dict "root" $jobValues "component" "jobserver" -}}
{{- $jobResourceName := printf "%s-job" (include "icm-as.fullname" $jobValues) -}}
{{- if ne $jobServerKey "default" -}}
{{- $jobResourceName = printf "%s-%s" $jobResourceName $jobServerKey -}}
{{- end -}}

{{ printf "\n---\n" }}
apiVersion: batch.core.intershop.de/v1
kind: ICMJob
metadata:
  name: {{ $jobResourceName }}
  {{- include "icm-as.podData" $jobValues | nindent 2 }}
  labels:
    {{- include "icm-as.labels" $ctx | nindent 4 }}
    {{- include "icm-as.podLabels" $jobValues | nindent 4 }}
    {{- if include "icm-as.podBinding" $jobValues }}
      {{- include "icm-as.podBinding" $jobValues | nindent 8 }}
    {{- end }}
    {{- if include "icm-as.serviceAccount.podLabels" $jobValues -}}
      {{- include "icm-as.serviceAccount.podLabels" $jobValues | nindent 4 }}
    {{- end }}
spec:
  scheduleTimeComputer: {{ include "icm-as.scheduleTimeComputer" $jobValues -}}
  {{- if $effectiveValues.suspend }}
  suspend: {{ $effectiveValues.suspend }}
  {{- end }}
  {{- if $effectiveValues.pollInterval }}
  pollInterval: {{ $effectiveValues.pollInterval }}
  {{- end }}
  {{- if $effectiveValues.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $effectiveValues.failedJobsHistoryLimit }}
  {{- end }}
  {{- if $effectiveValues.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ $effectiveValues.successfulJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if include "icm-as.serviceAccount.podSpec" $jobValues -}}
            {{- include "icm-as.serviceAccount.podSpec" $jobValues | nindent 10 }}
          {{- end }}
          {{- if include "icm-as.nodeSelector" $jobValues }}
            {{- include "icm-as.nodeSelector" $jobValues | nindent 10 }}
          {{- end }}
          {{- if include "icm-as.imagePullSecrets" $jobValues }}
            {{- include "icm-as.imagePullSecrets" $jobValues | nindent 10 }}
          {{- end }}
          containers:
          - name: icm-as-server
            {{- include "icm-as.command" (list $effectiveValues.customCommand false) | nindent 12 }}
            {{- include "icm-as.image" $jobValues | nindent 12 }}
            {{- include "icm-as.envJob" $jobValues | nindent 12 }}
            {{- include "icm-as.ports" $jobValues | nindent 12 }}
            {{- include "icm-as.resources" $jobValues | nindent 12 }}
            {{- include "icm-as.volumeMounts" $jobValues | nindent 12 }}
            {{- include "icm-as.probes" $jobValues | nindent 12 }}
            {{- include "icm-as.lifecycle" $jobValues | nindent 12 }}
          {{- include "icm-as.initContainers" $jobValues | nindent 10 }}
          restartPolicy: OnFailure
          {{- if include "icm-as.podSecurityContext" $jobValues }}
            {{- include "icm-as.podSecurityContext" $jobValues | nindent 10 }}
          {{- end }}
          {{- if include "icm-as.hostAliases" $jobValues }}
            {{- include "icm-as.hostAliases" $jobValues | nindent 10 }}
          {{- end }}
          {{- if include "icm-as.dnsConfig" $jobValues }}
            {{- include "icm-as.dnsConfig" $jobValues | nindent 10 }}
          {{- end }}
          {{- include "icm-as.volumes" $jobValues | nindent 10 }}
{{- end }}
{{- end -}}

{{/*
Job-scheduling service
*/}}
{{- define "icm-as.scheduleTimeComputer" -}}
{{- $params := print "serverGroup=" .jobServerGroup -}}
{{- if .Values.nameSpecific -}}
{{- $params = print $params "&serverName=" .jobServerName -}}
{{- end -}}
http://{{ include "icm-as.fullname" . }}.{{.Release.Namespace}}:7744/jobserver/nextScheduleDate?{{ $params }}
{{- end -}}
